title: Charlotte d'Huart
logo: img/charlotte25.png
description: <insert> Hi, I'm a freelance Data Analyst, feel free to contact me ! <br> <br> <insert/>
show_downloads: false
theme: jekyll-theme-minimal
